project = 'Twig'
copyright = '2021, OSCLab.com'
author = 'Ruden'
release = '3.0'
extensions = ['sphinx.ext.githubpages']
language = 'ru'
exclude_patterns = ['README*']
html_theme = 'furo'
html_static_path = ['_static']
html_show_sphinx = False
html_copy_source = False