name: Documentation

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  doctor-rst:
    name: DOCtor-RST

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run DOCtor-RST
        uses: docker://oskarstark/doctor-rst
        with:
          args: --short
        env:
          DOCS_DIR: 'doc/'